# Generated by Django 5.0 on 2024-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="thumbnail",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
